### ISSUE TITLE
Can't get current login account info 

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/cloud-cli#21]
$ cldi account -h
cldi-account
Manage account

USAGE:
    cldi account [SUBCOMMAND]

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    create    Create an account
    delete    Delete an account
    export    Export an account
    help      Print this message or the help of the given subcommand(s)
    import    Import an account
    login     Login to use the user's account as default

CLI will use the account has login, but we can't show current log account.

**Comment by whfuyn** [comment]
In `cloud-cli v0.3.0`, we can inspect the current account by checking the current context info.
```
$ cldi context list
# or 
$ cldi ctx l
```
