### ISSUE TITLE
COPYRIGHT

### ISSUE THREAD

**Issue by Pencil-Yao** [cita-cloud/cloud-cli#26]
https://github.com/cita-cloud/cloud-cli/blob/fb7a520dcfdbaadb203e6f501c6b3224e9312944/LICENSE#L189
修改为
`Copyright Rivtower Technologies LLC.`

**Comment by whfuyn** [comment]
这个应该是介绍怎么使用Apache协议，[上面](https://github.com/cita-cloud/cloud-cli/blob/fb7a520dcfdbaadb203e6f501c6b3224e9312944/LICENSE#L178)有提到。

之前也注意到了这个，对照了一下k8s的[license](https://github.com/kubernetes/kubernetes/blob/e1c16d24a101188d9ce6ffe8432de6ba60ab5efb/LICENSES/LICENSE#L193)也这样写的，感觉这样就行。

**Comment by rink1969** [comment]
是的，下面那段其实就是我们在每个文件头上加的那段`copyright`。那里我们是替换了方括弧内的内容的。
`http://www.apache.org/licenses/LICENSE-2.0`这个链接指向的就是这个LICENSE文件本身。

之前在另外一个PR里讨论过，其实仓库根目录放这个LICENSE文件不是必须的。
如果有其他开发者要使用我们的源码，按照文件头上的链接也可以看到这个LICENSE信息。

这里加这个文件是为了让github右侧能直接显示该仓库使用的开源协议，更加直观一些。
这个文件也是在github创建仓库，选择license之后，github默认就提供的，不需要改动。
